apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard
  namespace: argocd
spec:
  destination:
    name: poc-team-1
    namespace: adguard
  project: team-yolo
  source:
    targetRevision: main
    path: k8s/adguard
    repoURL: https://github.com/frealmyr/argo-poc-team-alpha
    helm:
      releaseName: adguard
